artifact_uri: file:///Users/macbookpro/Desktop/DIC3/mlops/projet/projet_mlops/NLP_Disaster_Tweets-/mlflow/487537303465525025/cf7575ddde4a42fc83c3d206b510dd2a/artifacts
end_time: 1780701499968
entry_point_name: ''
experiment_id: '487537303465525025'
lifecycle_stage: active
run_id: cf7575ddde4a42fc83c3d206b510dd2a
run_name: LR_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1780701492645
status: 3
tags: []
user_id: macbookpro
