artifact_uri: file:///Users/macbookpro/Desktop/DIC3/mlops/projet/projet_mlops/NLP_Disaster_Tweets-/mlflow/487537303465525025/6b8897ada5444469958fcaf2882882fd/artifacts
end_time: 1780702085558
entry_point_name: ''
experiment_id: '487537303465525025'
lifecycle_stage: active
run_id: 6b8897ada5444469958fcaf2882882fd
run_name: XGBoost_optuna
source_name: ''
source_type: 4
source_version: ''
start_time: 1780702079366
status: 3
tags: []
user_id: macbookpro
