artifact_uri: file:///Users/macbookpro/Desktop/DIC3/mlops/projet/projet_mlops/NLP_Disaster_Tweets-/mlflow/487537303465525025/7134300357614adbbac51a2e1ba433e2/artifacts
end_time: 1780772496968
entry_point_name: ''
experiment_id: '487537303465525025'
lifecycle_stage: active
run_id: 7134300357614adbbac51a2e1ba433e2
run_name: LR_optuna
source_name: ''
source_type: 4
source_version: ''
start_time: 1780772493288
status: 3
tags: []
user_id: macbookpro
