artifact_uri: file:///Users/macbookpro/Desktop/DIC3/mlops/projet/projet_mlops/NLP_Disaster_Tweets-/mlflow/487537303465525025/f63ee51a68834ce8b9bf3155dfef76c6/artifacts
end_time: 1780768523983
entry_point_name: ''
experiment_id: '487537303465525025'
lifecycle_stage: active
run_id: f63ee51a68834ce8b9bf3155dfef76c6
run_name: LinearSVC_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1780768518664
status: 3
tags: []
user_id: macbookpro
