artifact_location: file:///Users/macbookpro/Desktop/DIC3/mlops/projet/projet_mlops/NLP_Disaster_Tweets-/mlflow/487537303465525025
creation_time: 1780701052158
experiment_id: '487537303465525025'
last_update_time: 1780701052158
lifecycle_stage: active
name: disaster-tweet-classifier
