artifact_uri: file:///Users/macbookpro/Desktop/DIC3/mlops/projet/projet_mlops/NLP_Disaster_Tweets-/mlflow/487537303465525025/0cee3b30c2fb423ca69b8d1faf1c1638/artifacts
end_time: 1780773067175
entry_point_name: ''
experiment_id: '487537303465525025'
lifecycle_stage: active
run_id: 0cee3b30c2fb423ca69b8d1faf1c1638
run_name: LinearSVC_optuna
source_name: ''
source_type: 4
source_version: ''
start_time: 1780773062320
status: 3
tags: []
user_id: macbookpro
